import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Footer from '../component/Footer'
import Navbar from '../component/Navbar'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MyApp</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1 className={styles.title}>
          home page
      </h1>
    </div>
  )
}
