import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Intro from '../component/Intro'
import Services from '../component/services'
import { data, users } from './api/data'
import Testimonials from '../component/Testimonials'

export default function Home({ services, usersInfo }) {
  // console.log('services home page', services)

  return (
    <div className={styles.container}>
      <Head>
        <title>MyApp</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Intro />
      <Services services={services} />
      <Testimonials users={usersInfo}/>
    </div>
  )
}

export const getStaticProps = () => {
  const services = data
  const usersInfo = users
  // console.log('services', services);
  return {
    props: {
      services,
      usersInfo,
    }
  }
}
