import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Intro from '../component/Intro'
import Services from '../component/services'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MyApp</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Intro />
      <Services/>
    </div>
  )
}
